project_id = 'sas-sandbox-advanced-analytics'

bucket_name = 'interviewer'

client_id = '496650483213-upnomdusp1jjc2jbhocm1ngv51h162de.apps.googleusercontent.com'

client_secret = 'ScajIvavQaa1lNSnrbRPT3B_'

redirect_uri = 'http://localhost:8501'