project_id = 'sas-sandbox-advanced-analytics'

bucket_name = 'interviewer'

client_id = '496650483213-s1o6ii98d31r44cklmvv17q18eiml0ct.apps.googleusercontent.com'

client_secret = 'ZTs3XGNOu4r4jKRwW9AX0Qb-'

redirect_uri = 'https://share.streamlit.io/nascimentojuliana/interviewer/main/main.py'